### ISSUE TITLE
Jumping to commit

### ISSUE THREAD

**Issue by tobyf93** [MadRabbit/git-wayback-machine#6]
I am having issues jumping to a commit.  ENTER is not being recognised as a control...

**Comment by scalp42** [comment]
Can confirm @tobyf93 ENTER is not working on macos

**Comment by tobyf93** [comment]
Good to know i'm not going crazy

**Comment by tobyf93** [comment]
Just had a bit of a look in the code.  on_change in navigator.rb is not even handling the :enter event?  Jumping to commits work if you have the program running in a separate TAB (and don't close it) but that seems pretty inconvenient...

**Comment by kaievns** [comment]
hey @tobyf93, @scalp42  

there is no ENTER. the jump happens right away, when you navigate to the next item on the list.

If you're going to change it, plz make sure it clearly displays in which state the branch currently is :)

**Comment by scalp42** [comment]
Still confused how that work @MadRabbit

**Comment by kaievns** [comment]
@scalp42 em... just press `up` and `down` :) as soon as you go to the next item on the list it will automatically flip your repo's state to that commit

**Comment by tobyf93** [comment]
@scalp42:  I believe it's intended to be used in a separate TAB.

**Comment by scalp42** [comment]
I see, I thought it was more, my bad :smile:
