### ISSUE TITLE
Documentation 

### ISSUE THREAD

**Issue by tobyf93** [MadRabbit/git-wayback-machine#7]
**After checking out the repo, run bin/setup to install dependencies. Then, run bin/console for an interactive prompt that will allow you to experiment.**
bin/setup doesn't exist, nor does bin/console

**To install this gem onto your local machine, run bundle exec rake install. To release a new version, update the version number in version.rb, and then run bundle exec rake release to create a git tag for the version, push git commits and tags, and push the .gem file to rubygems.org.**
No Rakefile in directory

**Comment by kaievns** [comment]
i don't think `bit/setup` and `bin/console` are necessary, same for a `Rakefile` it is not really a gem in a normal sense, it is never intended to be integrated. it's just a bin script for `git` pipes
